spring:
  datasource:
    url: jdbc:postgresql://k10a105.p.ssafy.io:5432/cg
    username: cg
    password: cg!@#
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: k10a105.p.ssafy.io
      port: 6379
      password: cg!@#
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 114132095674-k7dug126d5oa5d4cubnrhamenj1155pt.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://${com.farmirang.user.login.redirect.host}:8081/api/v1/security/code/google"
            scope:
              - email

          kakao:
            client-id: fa6062b096597ce45f5b22eef416c8ea
            client-secret: MnjAVzbdzOihONinQnjBUvEYaNDeQBxD
            authorization-grant-type: authorization_code
            redirect-uri: "http://${com.farmirang.user.login.redirect.host}:8081/api/v1/security/code/kakao"
            client-name: kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
            jwk-set-uri: https://kauth.kakao.com/.well-known/jwks.json

cloud:
  aws:
    s3:
      bucket: wp-ht-s3
    credentials:
      access-key: AKIA4MDWI2KWXGRMYXSC
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

com:
  farmirang:
    user:
      s3_url: https://wp-ht-s3.s3.ap-northeast-2.amazonaws.com
      s3_dir: farmirang/profile
      default_profile: ${com.farmirang.user.s3_url}/${com.farmirang.user.s3_dir}/default.png
      login:
        redirect:
          host: k10a105.p.ssafy.io
        result: http://${com.farmirang.user.login.redirect.host}:3000/result